### ISSUE TITLE
Duplicut not cutting all duplicates

### ISSUE THREAD

**Issue by mariuskimmina** [nil0x42/duplicut#39]
I tested duplicut on a VM with files larger than RAM (2GB of RAM), I create a test file with  

```
yes this is test file | head -c 4GB > test.file
```

This create a 4GB file where every line is `this is test file`  
I used duplicut on the file  

```
duplicut test.file -o test.duplicut
```

Once it finished I expected `test.duplicut` to have exactly 1 line but to my suprise there were a couple of lines left, 9 to be exact.  
All 9 lines where the same `this is test file`.  
This seems odd and I decided to run duplicut again on `test.duplicut`

```
duplicut test.duplicut -o test.duplicut.2
```

After this second run, there is only 1 line left as I expected it from the beginning.  

Since this is so strange, I decided to test the same thing again:

```
duplicut test.file -o second.test.duplicut
```

But there are exactly 9 lines left again - I have no Idea why this happens but it is reproducible.

**Comment by nil0x42** [comment]
very strange indeed, i'm gonna investigate.

please tell me, are you in 32 or 64bit ?

**Comment by mariuskimmina** [comment]
It's a 64 bit system, see the Screenshot below for more details.

![debian](https://user-images.githubusercontent.com/38843153/146331592-80732ff2-8c4a-42fe-8cac-0bce7784626b.png)

If I can assist with my anything else, let me know

**Comment by nil0x42** [comment]
Hi ! Thank you very much for reporting this awful & critical bug !

The issue should be fixed now, please test with latest commits pushed on master.
Feel free to stress test duplicut as much as you can, i'll try to add a nonreg test for this case tomorrow.

**Comment by nil0x42** [comment]
Humm, it looks like i didn't properly fix it.
I'm tired now, need to investigate more tomorrow.

**Comment by mariuskimmina** [comment]
I know you said it's not fixed yet but I tested the changes anyway, the result is slightly different now.
I tested it with the same 4GB files full of `this is test file`. Instead of 9 lines I know have 10 lines left where the 10th line is `this` instead of `this is test file`.

![duplicut-test-newbuild](https://user-images.githubusercontent.com/38843153/146517903-2b3f079e-5537-4883-8239-28245bdffd61.png)


I hope you have a good night of sleep, don't stress yourself over something you are doing voluntary, you are doing a really good job!

**Comment by nil0x42** [comment]
Hi ! please try again, should be fixed now!

note that when you generate lines with `yes`, and truncate to N bytes, the last line might be truncated, so if your test file's last line only contains `this is a t`, then it's normal that duplicut will see 2 different lines (`this is a test file` and `this is a t`)

**Comment by mariuskimmina** [comment]
Hey, thank you, now it works exactly as expected!

Great Job!
